### PR TITLE
Ft user favorite article 159054018

### PR DESCRIPTION
**Pull request by Duncanian**
**What does this PR do?**
Implements favoriting and unfavoriting an article(s)

**background Information.**
Enables a user to favorite articles that tick their fancy and they can also unfavorite the article.
Only authenticated users can favorite and unfavorite articles

**How To Manually Test?**

Pull ft-user-favorite-article-159054018
`git pull ft-user-favorite-article-159054018`

Checkout to ft-user-favorite-article-159054018 branch
`git checkout ft-user-favorite-article-159054018`

Update database by running migrations.
   `python manage.py makemigrations`
   `python manage.py migrate`

Start the server
`python manage.py runserver`

Test the endpoints on postman.

Run test coverage
`coverage run manage.py test`
`coverage report`

**Affected Endpoints:**
`POST /api/articles/<slug>/favorite`

RESPONSE
```
{
    "favorites": {
        "title": "I love code",
        "slug": "i-love-code-fvw5c0c5uw",
        "body": "God this is awesome",
        "description": "",
        "image_url": null,
        "created_at": "2018-08-07T07:36:41.292159Z",
        "updated_at": "2018-08-07T07:36:41.292217Z",
        "favorited": true,
        "favoriteCount": 1,
        "author": {
            "username": "ian",
            "bio": "",
            "image": "https://static.productionready.io/images/smiley-cyrus.jpg"
        }
    }
}
```

`GET /api/articles/<slug>/favorite`

RESPONSE
```
{
    "favorites": {
        "title": "I love code",
        "slug": "i-love-code-fvw5c0c5uw",
        "body": "God this is shit",
        "description": "",
        "image_url": null,
        "created_at": "2018-08-07T07:36:41.292159Z",
        "updated_at": "2018-08-07T07:36:41.292217Z",
        "favorited": true,
        "favoriteCount": 1,
        "author": {
            "username": "ian",
            "bio": "",
            "image": "https://static.productionready.io/images/smiley-cyrus.jpg"
        }
    }
}
```

`DELETE /api/articles/<slug>/favorite`

RESPONSE
```
{
    "favorites": {
        "title": "I love code",
        "slug": "i-love-code-fvw5c0c5uw",
        "body": "God this is shit",
        "description": "",
        "image_url": null,
        "created_at": "2018-08-07T07:36:41.292159Z",
        "updated_at": "2018-08-07T07:36:41.292217Z",
        "favorited": false,
        "favoriteCount": 0,
        "author": {
            "username": "ian",
            "bio": "",
            "image": "https://static.productionready.io/images/smiley-cyrus.jpg"
        }
    }
}
```
What are the relevant pivotal tracker stories?

[#159054018](https://www.pivotaltracker.com/story/show/159054018) Users should be able to favorite articles

### CODE REVIEW

**Comment by Tittoh** [comment]
You can raise the test coverage by pulling develop. More tests were added for the views.

**Comment by Duncanian** [comment]
@Tittoh , I pulled develop and updated my PR and still there is a decrease

**Comment by jacksono** [comment]
@Duncanian you can look at the coverage report on the coveralls page and see which lines are not covered in the test. @dessHub  can help you out with this. Our test coverage should either increase or remain the same except in cases where we don't have control or where we intend to handle the coverage later.

**Comment by Duncanian** [comment]
@jacksono , Am on it now with @dessHub

**Review by jacksono — APPROVED** [review]
Works as required

**Pull request merged**
