### PR TITLE
#159054000 Implement feedback

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Implement given feedback

#### Description of Task to be completed?
- Fix grammatical typo on authors haven
- Change all links color from blue to green

#### How should this be manually tested?
Follow the guidelines provided on the mockup.md file

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#159054000](https://www.pivotaltracker.com/story/show/159054000)

##### Social signin page
social_signin

##### Signin with email page
email_signin

##### Signup page
signup

### CODE REVIEW

**Comment by jacksono** [comment]
@DennisWanjiru The screenshots on the PR description look ok but when I tried to run your branch on my computer I got a number of errors.. see the screen shots below:
screen shot 2018-07-28 at 18 17 54
screen shot 2018-07-28 at 18 18 13
screen shot 2018-07-28 at 18 18 43
screen shot 2018-07-28 at 18 19 14

**Comment by denniswanjiru** [comment]
@jacksono I think I need to configure a way to serve the ui

**Comment by denniswanjiru** [comment]
@jacksono The PR is ready for final review.

**Review by jacksono — APPROVED** [review]
It's all working well now.

**Pull request merged**
