### PR TITLE
#159792429 Write test fro likes and dislikes

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Write test for likes and dislikes

#### Description of Task to be completed?
- Write tests likes and dislikes

#### How should this be manually tested?
- Clone this branch

```
git clone -b  ch-test-dislike-like-159792429 git@github.com:andela/ah-jarvis.git

cd ah-jarvis
  
create and activate a virtual env 

pip install -r requirements.txt

python manage.py migrate

coverage manage.py test

```

#### What are the relevant pivotal tracker stories?
[#159792429](https://www.pivotaltracker.com/story/show/159054017/comments/159792429)

### CODE REVIEW

**Comment by jacksono** [comment]
@DennisWanjiru good job on getting this done. Just merge the latest changes from develop into this branch then I can merge this in.

**Comment by denniswanjiru** [comment]
@jacksono  I just pulled the develop branch locally but it said `nothing to commit, working tree clean`

**Comment by jacksono** [comment]
@DennisWanjiru its possible you forgot to first pull the changes into your local develop branch. I have made the change through Github now

**Review by jacksono — APPROVED** [review]

**Comment by DennisWanjiru** [comment]
@Duncanian What you mean with something wrong? Could you please clarify?

**Pull request merged**
