### PR TITLE
#159054009 Implement email verification

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Implement email verification

#### Description of Task to be completed?
- Send a verification email on a successful registration
- Verify account on clicking the sent verification link

#### How should this be manually tested?
- Clone this branch
- Create an account with sendgrid and acquire an apikey. 
- Add the api key to the .env as follows 
` EMAIL_HOST_PASSWORD=YOUR_SENDGRID_API_KEY `

``` 
cd ah-jarvis

create and activate a virtual env 

pip install -r requirements.txt

python manage.py makemigrations

python manage.py migrate

coverage run manage.py test

python manage.py run server

```

- Open your postman and create an account with your valid email as follows

```
{
  "user": {
	"username":"jake",
	"email":"validemail@example.com",
	"password":"Pass1234"
  }
}
```

- Open your email and find an email from `webmaster@localhost`
- Try to verify your account
- Boom! There you go, your account is now verified

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#159054009](https://www.pivotaltracker.com/story/show/159054009)

##### Email mockup
email

### CODE REVIEW

**Comment by dessHub** [comment]
@DennisWanjiru  I have pulled your branch and I noticed some issues you need to address on your PR description. First you need to mention that `EMAIL_HOST_PASSWORD` variable needs to be set in evn file. Secondly since you updated user model, you should mention that, migrations should be made before testing. 
Finally i'm getting an error when creating a user. It does create the user but can't send the email. Below is the last bit of the error.

`smtplib.SMTPServerDisconnected: Connection unexpectedly closed`

**Comment by denniswanjiru** [comment]
@dessHub I updated my guide on how to manually test. You need your own API KEY from Sendgrid

**Comment by asamisellah** [comment]
@DennisWanjiru There's a step for running migrations that is not included before `python manage.py runserver`.

**Comment by asamisellah** [comment]
I have tested your feature and it works as expected

**Comment by Duncanian** [comment]
@DennisWanjiru , I tested it and got this message after verifying `Account was verified successfully`. It works fine for me.

**Review by jacksono — DISMISSED** [review]

**Comment by denniswanjiru** [comment]
@jacksono This PR is ready for final review

**Comment by jacksono** [comment]
@DennisWanjiru there is still a conflict to be resolved

**Comment by denniswanjiru** [comment]
@jacksono I Just fixed conflicts.

**Review by jacksono — APPROVED** [review]

**Comment by dwarukira** [comment]
Your implementation is good. But I think based on the andela git best practices guideline, You should name your GIT branches Following the given convention.

**Pull request merged**
